# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: messages.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class MType(betterproto.Enum):
    UNKNOWN = 0
    PLAYER_LOGIN = 1
    MOUSE_EVENT = 2
    PING_EVENT = 3


@dataclass
class PlayerLogin(betterproto.Message):
    username: str = betterproto.string_field(1)
    password: str = betterproto.string_field(2)


@dataclass
class MouseEvent(betterproto.Message):
    x: int = betterproto.int32_field(1)
    y: int = betterproto.int32_field(2)
    left_click: bool = betterproto.bool_field(3)
    right_click: bool = betterproto.bool_field(4)


@dataclass
class Ping(betterproto.Message):
    sent_epoch: int = betterproto.uint64_field(1)
    bounce_epoch: int = betterproto.uint64_field(2)
    received_epoch: int = betterproto.uint64_field(3)
