// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: messages.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TurretRotation int32

const (
	TurretRotation_CW    TurretRotation = 0
	TurretRotation_CCW   TurretRotation = 1
	TurretRotation_STILL TurretRotation = 2
)

// Enum value maps for TurretRotation.
var (
	TurretRotation_name = map[int32]string{
		0: "CW",
		1: "CCW",
		2: "STILL",
	}
	TurretRotation_value = map[string]int32{
		"CW":    0,
		"CCW":   1,
		"STILL": 2,
	}
)

func (x TurretRotation) Enum() *TurretRotation {
	p := new(TurretRotation)
	*p = x
	return p
}

func (x TurretRotation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TurretRotation) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (TurretRotation) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x TurretRotation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TurretRotation.Descriptor instead.
func (TurretRotation) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type PlayerLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *PlayerLogin) Reset() {
	*x = PlayerLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLogin) ProtoMessage() {}

func (x *PlayerLogin) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLogin.ProtoReflect.Descriptor instead.
func (*PlayerLogin) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerLogin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PlayerLogout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *PlayerLogout) Reset() {
	*x = PlayerLogout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLogout) ProtoMessage() {}

func (x *PlayerLogout) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLogout.ProtoReflect.Descriptor instead.
func (*PlayerLogout) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerLogout) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sent     uint64 `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	Bounced  uint64 `protobuf:"varint,2,opt,name=bounced,proto3" json:"bounced,omitempty"`
	Received uint64 `protobuf:"varint,3,opt,name=received,proto3" json:"received,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Ping) GetSent() uint64 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *Ping) GetBounced() uint64 {
	if x != nil {
		return x.Bounced
	}
	return 0
}

func (x *Ping) GetReceived() uint64 {
	if x != nil {
		return x.Received
	}
	return 0
}

type MouseInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A bit special for a mouse-centric game
	MouseX     int32 `protobuf:"varint,1,opt,name=mouse_x,json=mouseX,proto3" json:"mouse_x,omitempty"`
	MouseY     int32 `protobuf:"varint,2,opt,name=mouse_y,json=mouseY,proto3" json:"mouse_y,omitempty"`
	RightClick bool  `protobuf:"varint,3,opt,name=right_click,json=rightClick,proto3" json:"right_click,omitempty"`
	LeftClick  bool  `protobuf:"varint,4,opt,name=left_click,json=leftClick,proto3" json:"left_click,omitempty"`
}

func (x *MouseInput) Reset() {
	*x = MouseInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MouseInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseInput) ProtoMessage() {}

func (x *MouseInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseInput.ProtoReflect.Descriptor instead.
func (*MouseInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *MouseInput) GetMouseX() int32 {
	if x != nil {
		return x.MouseX
	}
	return 0
}

func (x *MouseInput) GetMouseY() int32 {
	if x != nil {
		return x.MouseY
	}
	return 0
}

func (x *MouseInput) GetRightClick() bool {
	if x != nil {
		return x.RightClick
	}
	return false
}

func (x *MouseInput) GetLeftClick() bool {
	if x != nil {
		return x.LeftClick
	}
	return false
}

type WASDInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Keyboard-centric input
	Forward  int32 `protobuf:"varint,1,opt,name=forward,proto3" json:"forward,omitempty"`
	Backward int32 `protobuf:"varint,2,opt,name=backward,proto3" json:"backward,omitempty"`
	Right    int32 `protobuf:"varint,3,opt,name=right,proto3" json:"right,omitempty"`
	Left     int32 `protobuf:"varint,4,opt,name=left,proto3" json:"left,omitempty"`
}

func (x *WASDInput) Reset() {
	*x = WASDInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WASDInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WASDInput) ProtoMessage() {}

func (x *WASDInput) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WASDInput.ProtoReflect.Descriptor instead.
func (*WASDInput) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *WASDInput) GetForward() int32 {
	if x != nil {
		return x.Forward
	}
	return 0
}

func (x *WASDInput) GetBackward() int32 {
	if x != nil {
		return x.Backward
	}
	return 0
}

func (x *WASDInput) GetRight() int32 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *WASDInput) GetLeft() int32 {
	if x != nil {
		return x.Left
	}
	return 0
}

type TankStyleMovement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TurretRotation TurretRotation `protobuf:"varint,1,opt,name=turretRotation,proto3,enum=messages.TurretRotation" json:"turretRotation,omitempty"`
	Forward        int32          `protobuf:"varint,2,opt,name=forward,proto3" json:"forward,omitempty"`
	Backward       int32          `protobuf:"varint,3,opt,name=backward,proto3" json:"backward,omitempty"`
	Right          int32          `protobuf:"varint,4,opt,name=right,proto3" json:"right,omitempty"`
	Left           int32          `protobuf:"varint,5,opt,name=left,proto3" json:"left,omitempty"`
}

func (x *TankStyleMovement) Reset() {
	*x = TankStyleMovement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TankStyleMovement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TankStyleMovement) ProtoMessage() {}

func (x *TankStyleMovement) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TankStyleMovement.ProtoReflect.Descriptor instead.
func (*TankStyleMovement) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *TankStyleMovement) GetTurretRotation() TurretRotation {
	if x != nil {
		return x.TurretRotation
	}
	return TurretRotation_CW
}

func (x *TankStyleMovement) GetForward() int32 {
	if x != nil {
		return x.Forward
	}
	return 0
}

func (x *TankStyleMovement) GetBackward() int32 {
	if x != nil {
		return x.Backward
	}
	return 0
}

func (x *TankStyleMovement) GetRight() int32 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *TankStyleMovement) GetLeft() int32 {
	if x != nil {
		return x.Left
	}
	return 0
}

// GameObjectEvent:
// Sent by server to clients.
// Manages lifecycle and basic properties of all GameObjects.
// Other more specific events for certain classes sets more
// specific attributes.
//
// Client:
// - SPAWNS or REMOVES representations.
type GameObjectEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// Server frame this happened in
	Tick int64 `protobuf:"varint,2,opt,name=Tick,proto3" json:"Tick,omitempty"`
	// What class (on client typically) to spawn.
	Kind string `protobuf:"bytes,3,opt,name=Kind,proto3" json:"Kind,omitempty"`
	// If explicit action, like create, delete, hide, show etc.
	Action string `protobuf:"bytes,4,opt,name=Action,proto3" json:"Action,omitempty"`
	// Translation within current segment
	X int32 `protobuf:"varint,5,opt,name=X,proto3" json:"X,omitempty"`
	Y int32 `protobuf:"varint,6,opt,name=Y,proto3" json:"Y,omitempty"`
	Z int32 `protobuf:"varint,7,opt,name=Z,proto3" json:"Z,omitempty"`
	// Width and height
	W int32 `protobuf:"varint,8,opt,name=W,proto3" json:"W,omitempty"`
	H int32 `protobuf:"varint,9,opt,name=H,proto3" json:"H,omitempty"`
	// Rotation in degrees
	R int32 `protobuf:"varint,10,opt,name=R,proto3" json:"R,omitempty"`
	// Initial values for this specific class to be set during this action
	Attributes map[string]string `protobuf:"bytes,11,rep,name=Attributes,proto3" json:"Attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GameObjectEvent) Reset() {
	*x = GameObjectEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameObjectEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameObjectEvent) ProtoMessage() {}

func (x *GameObjectEvent) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameObjectEvent.ProtoReflect.Descriptor instead.
func (*GameObjectEvent) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GameObjectEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameObjectEvent) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *GameObjectEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GameObjectEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GameObjectEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GameObjectEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *GameObjectEvent) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *GameObjectEvent) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *GameObjectEvent) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *GameObjectEvent) GetR() int32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *GameObjectEvent) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// https://protobuf.dev/programming-guides/proto3/#maps
type SetGameObjectAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Attributes map[string]string `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SetGameObjectAttributes) Reset() {
	*x = SetGameObjectAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetGameObjectAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGameObjectAttributes) ProtoMessage() {}

func (x *SetGameObjectAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGameObjectAttributes.ProtoReflect.Descriptor instead.
func (*SetGameObjectAttributes) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SetGameObjectAttributes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetGameObjectAttributes) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*Packet_PlayerLogin
	//	*Packet_PlayerLogout
	//	*Packet_Ping
	//	*Packet_MouseInput
	//	*Packet_WasdInput
	//	*Packet_GameObjectEvent
	//	*Packet_SetGameObjectAttributes
	Payload isPacket_Payload `protobuf_oneof:"payload"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (m *Packet) GetPayload() isPacket_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Packet) GetPlayerLogin() *PlayerLogin {
	if x, ok := x.GetPayload().(*Packet_PlayerLogin); ok {
		return x.PlayerLogin
	}
	return nil
}

func (x *Packet) GetPlayerLogout() *PlayerLogout {
	if x, ok := x.GetPayload().(*Packet_PlayerLogout); ok {
		return x.PlayerLogout
	}
	return nil
}

func (x *Packet) GetPing() *Ping {
	if x, ok := x.GetPayload().(*Packet_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *Packet) GetMouseInput() *MouseInput {
	if x, ok := x.GetPayload().(*Packet_MouseInput); ok {
		return x.MouseInput
	}
	return nil
}

func (x *Packet) GetWasdInput() *WASDInput {
	if x, ok := x.GetPayload().(*Packet_WasdInput); ok {
		return x.WasdInput
	}
	return nil
}

func (x *Packet) GetGameObjectEvent() *GameObjectEvent {
	if x, ok := x.GetPayload().(*Packet_GameObjectEvent); ok {
		return x.GameObjectEvent
	}
	return nil
}

func (x *Packet) GetSetGameObjectAttributes() *SetGameObjectAttributes {
	if x, ok := x.GetPayload().(*Packet_SetGameObjectAttributes); ok {
		return x.SetGameObjectAttributes
	}
	return nil
}

type isPacket_Payload interface {
	isPacket_Payload()
}

type Packet_PlayerLogin struct {
	PlayerLogin *PlayerLogin `protobuf:"bytes,1,opt,name=playerLogin,proto3,oneof"`
}

type Packet_PlayerLogout struct {
	PlayerLogout *PlayerLogout `protobuf:"bytes,2,opt,name=playerLogout,proto3,oneof"`
}

type Packet_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type Packet_MouseInput struct {
	MouseInput *MouseInput `protobuf:"bytes,4,opt,name=mouseInput,proto3,oneof"`
}

type Packet_WasdInput struct {
	WasdInput *WASDInput `protobuf:"bytes,5,opt,name=wasdInput,proto3,oneof"`
}

type Packet_GameObjectEvent struct {
	GameObjectEvent *GameObjectEvent `protobuf:"bytes,10,opt,name=gameObjectEvent,proto3,oneof"`
}

type Packet_SetGameObjectAttributes struct {
	SetGameObjectAttributes *SetGameObjectAttributes `protobuf:"bytes,11,opt,name=setGameObjectAttributes,proto3,oneof"`
}

func (*Packet_PlayerLogin) isPacket_Payload() {}

func (*Packet_PlayerLogout) isPacket_Payload() {}

func (*Packet_Ping) isPacket_Payload() {}

func (*Packet_MouseInput) isPacket_Payload() {}

func (*Packet_WasdInput) isPacket_Payload() {}

func (*Packet_GameObjectEvent) isPacket_Payload() {}

func (*Packet_SetGameObjectAttributes) isPacket_Payload() {}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x45, 0x0a, 0x0b, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x2a, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a,
	0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6f, 0x75,
	0x6e, 0x63, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x6f, 0x75, 0x6e,
	0x63, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x22,
	0x7e, 0x0a, 0x0a, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x6d, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6d, 0x6f, 0x75, 0x73, 0x65, 0x58, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x6f, 0x75, 0x73, 0x65, 0x5f,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x6f, 0x75, 0x73, 0x65, 0x59, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x72, 0x69, 0x67, 0x68, 0x74, 0x43, 0x6c, 0x69, 0x63, 0x6b,
	0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6c, 0x65, 0x66, 0x74, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x22,
	0x6b, 0x0a, 0x09, 0x57, 0x41, 0x53, 0x44, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x66,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x77, 0x61,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x77, 0x61,
	0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x22, 0xb5, 0x01, 0x0a,
	0x11, 0x54, 0x61, 0x6e, 0x6b, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x40, 0x0a, 0x0e, 0x74, 0x75, 0x72, 0x72, 0x65, 0x74, 0x52, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x54, 0x75, 0x72, 0x72, 0x65, 0x74, 0x52, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x74, 0x75, 0x72, 0x72, 0x65, 0x74, 0x52, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x77, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x77, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x6c, 0x65, 0x66, 0x74, 0x22, 0xbf, 0x02, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x63, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04,
	0x4b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4b, 0x69, 0x6e, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x59, 0x12, 0x0c, 0x0a, 0x01, 0x5a, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x5a, 0x12, 0x0c, 0x0a, 0x01, 0x57, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x57,
	0x12, 0x0c, 0x0a, 0x01, 0x48, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x48, 0x12, 0x0c,
	0x0a, 0x01, 0x52, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x52, 0x12, 0x49, 0x0a, 0x0a,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xbb, 0x01, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x51, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x53, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0xc5, 0x03, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x39, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x3c, 0x0a, 0x0c, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x36,
	0x0a, 0x0a, 0x6d, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x6f,
	0x75, 0x73, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x6d, 0x6f, 0x75, 0x73,
	0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x33, 0x0a, 0x09, 0x77, 0x61, 0x73, 0x64, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x57, 0x41, 0x53, 0x44, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x48, 0x00,
	0x52, 0x09, 0x77, 0x61, 0x73, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x45, 0x0a, 0x0f, 0x67,
	0x61, 0x6d, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48,
	0x00, 0x52, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x5d, 0x0a, 0x17, 0x73, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53,
	0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x48, 0x00, 0x52, 0x17, 0x73, 0x65, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x2c, 0x0a, 0x0e,
	0x54, 0x75, 0x72, 0x72, 0x65, 0x74, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x06,
	0x0a, 0x02, 0x43, 0x57, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x43, 0x57, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x53, 0x54, 0x49, 0x4c, 0x4c, 0x10, 0x02, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_messages_proto_goTypes = []interface{}{
	(TurretRotation)(0),             // 0: messages.TurretRotation
	(*PlayerLogin)(nil),             // 1: messages.PlayerLogin
	(*PlayerLogout)(nil),            // 2: messages.PlayerLogout
	(*Ping)(nil),                    // 3: messages.Ping
	(*MouseInput)(nil),              // 4: messages.MouseInput
	(*WASDInput)(nil),               // 5: messages.WASDInput
	(*TankStyleMovement)(nil),       // 6: messages.TankStyleMovement
	(*GameObjectEvent)(nil),         // 7: messages.GameObjectEvent
	(*SetGameObjectAttributes)(nil), // 8: messages.SetGameObjectAttributes
	(*Packet)(nil),                  // 9: messages.Packet
	nil,                             // 10: messages.GameObjectEvent.AttributesEntry
	nil,                             // 11: messages.SetGameObjectAttributes.AttributesEntry
}
var file_messages_proto_depIdxs = []int32{
	0,  // 0: messages.TankStyleMovement.turretRotation:type_name -> messages.TurretRotation
	10, // 1: messages.GameObjectEvent.Attributes:type_name -> messages.GameObjectEvent.AttributesEntry
	11, // 2: messages.SetGameObjectAttributes.attributes:type_name -> messages.SetGameObjectAttributes.AttributesEntry
	1,  // 3: messages.Packet.playerLogin:type_name -> messages.PlayerLogin
	2,  // 4: messages.Packet.playerLogout:type_name -> messages.PlayerLogout
	3,  // 5: messages.Packet.ping:type_name -> messages.Ping
	4,  // 6: messages.Packet.mouseInput:type_name -> messages.MouseInput
	5,  // 7: messages.Packet.wasdInput:type_name -> messages.WASDInput
	7,  // 8: messages.Packet.gameObjectEvent:type_name -> messages.GameObjectEvent
	8,  // 9: messages.Packet.setGameObjectAttributes:type_name -> messages.SetGameObjectAttributes
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerLogout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MouseInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WASDInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TankStyleMovement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameObjectEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetGameObjectAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_messages_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*Packet_PlayerLogin)(nil),
		(*Packet_PlayerLogout)(nil),
		(*Packet_Ping)(nil),
		(*Packet_MouseInput)(nil),
		(*Packet_WasdInput)(nil),
		(*Packet_GameObjectEvent)(nil),
		(*Packet_SetGameObjectAttributes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
