# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: messages.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerLogin(betterproto.Message):
    username: str = betterproto.string_field(1)
    password: str = betterproto.string_field(2)


@dataclass
class Ping(betterproto.Message):
    sent: float = betterproto.float_field(1)
    bounced: float = betterproto.float_field(2)
    received: float = betterproto.float_field(3)


@dataclass
class Packet(betterproto.Message):
    player_login: "PlayerLogin" = betterproto.message_field(2, group="the_message")
    ping: "Ping" = betterproto.message_field(3, group="the_message")
