# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: messages.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerLogin(betterproto.Message):
    username: str = betterproto.string_field(1)
    password: str = betterproto.string_field(2)


@dataclass
class Ping(betterproto.Message):
    sent: int = betterproto.uint64_field(1)
    bounced: int = betterproto.uint64_field(2)
    received: int = betterproto.uint64_field(3)


@dataclass
class MouseEvent(betterproto.Message):
    x: int = betterproto.int32_field(1)
    y: int = betterproto.int32_field(2)
    left_click: bool = betterproto.bool_field(3)
    right_click: bool = betterproto.bool_field(4)


@dataclass
class Packet(betterproto.Message):
    player_login: "PlayerLogin" = betterproto.message_field(1, group="the_message")
    ping: "Ping" = betterproto.message_field(2, group="the_message")
    mouse_event: "MouseEvent" = betterproto.message_field(3, group="the_message")
