# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install xorg-dev
      run: sudo apt-get install -y xorg-dev
  
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test Client
      run: go test -v ./...
      working-directory: wtf-main/client

    - name: Build Client
      run: go build -v ./...
      working-directory: wtf-main/client

    - name: Test Server
      run: go test -v ./...
      working-directory: wtf-main/server

    - name: Build Server
      run: go build -v ./...
      working-directory: wtf-main/server
