# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install xorg-dev
      run: sudo apt-get install -y xorg-dev
  
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test Shared
      working-directory: wtf-main/shared
      run: go test -v ./...

    - name: Test Client
      working-directory: wtf-main/client
      run: go test -v ./...

    - name: Build Client
      working-directory: wtf-main/client
      run: go build -v ./...

#    - name: Test Server
#      working-directory: wtf-main/server
#      run: go test -v ./...

#    - name: Build Server
#      working-directory: wtf-main/server
#      run: go build -v ./...
      
    - name: Upload Ubuntu Client Artefact
      uses: actions/upload-artifact@v3.1.2
      with: 
        name: ubuntu-client
        path: wtf-main/client/client

#    - name: Upload Ubuntu Server Artefact
#      uses: actions/upload-artifact@v3.1.2
#      with: 
#        name: ubuntu-server
#        path: wtf-main/server/server
