# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Executables
on: [push]

env:
  itchio_user: Hanserfaust
  itchio_project: Hanserfaust/wtf

jobs:

#  tests:
#    name: Run tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Install xorg-dev
#        run: sudo apt-get install -y xorg-dev
#
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.19
#
#      - name: Test Shared
#        working-directory: go-root/lib/shared
#        run: go test -v
#
#      - name: Test Client
#        working-directory: go-root/lib/client
#        run: go test -v
#
#      - name: Test Server
#        working-directory: go-root/server
#        run: go test -v

#  build-win-client:
#    name: Windows Client [Build]
#    needs: tests
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.19
#      - name: Build Windows exe
#        working-directory: go-root/client
#        shell: bash
#        run: go build -ldflags="-X main.Commit=$(git rev-parse HEAD)"
#      - name: Upload Windows exe
#        uses: actions/upload-artifact@v3
#        with:
#          path: go-root/client/client.exe
#          name: windows-client
#
#  win-client-itchio-upload:
#    name: Upload Windows client to Itch.io
#    needs: build-win-client
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/download-artifact@v3
#        with:
#          name: windows-client
#      - name: Display structure of downloaded files
#        run: ls -R
#      - name: Set Version
#        run: |
#          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
#      - name: Upload to itch.io project
#        # https://github.com/marketplace/actions/itch-io-upload
#        uses: robpc/itchio-upload-action@v1
#        with:
#          path: client.exe
#          project: ${{ env.itchio_project }}
#          channel: windows
#          version: ${{ env.version }}
#          api-key: ${{ secrets.ITCHIO_API_KEY }}
#
#  build-linux-client:
#    name: Build Linux Client
#    needs: tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.19
#      - name: Install dependencies
#        shell: bash
#        run: sudo apt-get update && sudo apt-get -y install libgl1-mesa-dev xorg-dev libasound2-dev
#      - name: Build Linux Client
#        working-directory: go-root/client
#        run: go build -v -ldflags="-X main.Commit=$(git rev-parse HEAD)"
#      - name: Upload Ubuntu Client Artefact
#        uses: actions/upload-artifact@v3.1.2
#        with:
#          name: linux-client
#          path: go-root/client/client
#
#  linux-client-itchio-upload:
#    name: Upload Linux client to Itch.io
#    needs: build-linux-client
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/download-artifact@v3
#        with:
#          name: linux-client
#      - name: Display structure of downloaded files
#        run: ls -R
#      - name: Set Version
#        run: |
#          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
#      - name: Upload to itch.io project
#        # https://github.com/marketplace/actions/itch-io-upload
#        uses: robpc/itchio-upload-action@v1
#        with:
#          path: client
#          project: ${{ env.itchio_project }}
#          channel: linux
#          version: ${{ env.version }}
#          api-key: ${{ secrets.ITCHIO_API_KEY }}
#
#  build-mac-client:
#    name: Build MacOS Client
#    needs: tests
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.19
#      - name: Build Mac Client
#        shell: bash
#        working-directory: go-root/client
#        run: go build -ldflags="-X main.Commit=$(git rev-parse HEAD)"
#      - name: Chmod on binary
#        shell: bash
#        working-directory: go-root/client
#        run: chmod +x client
#      - name: Upload Mac Bundle
#        uses: actions/upload-artifact@v3
#        with:
#          name: mac-client
#          path: go-root/client/client
#
#  mac-client-itchio-upload:
#    name: Upload Mac client to Itch.io
#    needs: build-mac-client
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - uses: actions/download-artifact@v3
#        with:
#          name: mac-client
#      - name: Display structure of downloaded files
#        run: ls -R
#      - name: Set Version
#        run: |
#          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
#      - name: Upload to itch.io project
#        # https://github.com/marketplace/actions/itch-io-upload
#        uses: robpc/itchio-upload-action@v1
#        with:
#          path: client
#          project: ${{ env.itchio_project }}
#          channel: mac
#          version: ${{ env.version }}
#          api-key: ${{ secrets.ITCHIO_API_KEY }}

  build-wasm-client:
    name: Build WASM client
#    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        shell: bash
        working-directory: go-root/gui-client
        # Connect to 888 for dev builds
        run: GOOS=js GOARCH=wasm go build -ldflags="-X 'main.Protocol=wss' -X 'main.WTFHost=wtf-dev-server.bitknife.se' -X 'main.WsPort=888' -w -s" -v -o ../wasm/main.wasm
      - name: Upload Web build
        uses: actions/upload-artifact@v3
        with:
          name: wasm-client
          path: |
            go-root/wasm/index.html
            go-root/wasm/main.wasm
            go-root/wasm/wasm_exec.js

  wasm-client-itchio-upload:
    name: Upload WASM client to Itch.io
    needs: build-wasm-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: wasm-client
          path: dist/wasm
      - name: Display structure of downloaded files
        run: ls -R
      - name: Set Version
        run: |
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Upload to itch.io project
        # https://github.com/marketplace/actions/itch-io-upload
        uses: robpc/itchio-upload-action@v1
        with:
          path: dist/wasm
          project: ${{ env.itchio_project }}
          channel: web
          version: ${{ env.version }}
          api-key: ${{ secrets.ITCHIO_API_KEY }}

  build-linux-server:
    name: Build And Upload Linux Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install dependencies
        shell: bash
        run: sudo apt-get update && sudo apt-get -y install libgl1-mesa-dev xorg-dev libasound2-dev
      - name: Build Linux server
        working-directory: go-root/server
        run: go build -v -ldflags="-X main.Commit=$(git rev-parse HEAD)"

      - name: Upload Linux Server Artefact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: linux-server
          path: go-root/server/server

#  install-linux-dev-server:
#    name: Install Linux Server
#    needs: build-linux-server
#    runs-on: ubuntu-latest
#    steps:
      # https://github.com/appleboy/scp-action
      - name: Upload to Dev Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          port: ${{ secrets.DEV_PORT }}
          source: "go-root/server/server,go-root/server/motif.txt"
          target: ~/wtf-dev-server/
          # Removes two levels of directories
          strip_components: 2
